apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-serve
  namespace: open-serve
spec:
  chartRef:
    kind: OCIRepository
    name: open-serve
    namespace: open-serve
  interval: 10m
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
