# Upstream prometheus-community Helm chart repository.
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: open-serve
spec:
  interval: 1h
  url: https://prometheus-community.github.io/helm-charts
