apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/kuberay-operator
configurations:
  - kustomizeconfig.yaml
configMapGenerator:
  - name: kuberay-operator-values
    namespace: open-serve
    files:
      - values.yaml=values.yaml
patches:
  - path: release.yaml
    target:
      kind: HelmRelease
